---
# tasks file for update-os
- name: Installing figlet for ASCII banner
  dnf:
    name: figlet
    state: present

- name: Setting up 
  shell: "figlet -c Server is going into maintenance mode for patching. > /etc/motd"  

- name: Prevent non-root user login
  lineinfile:
    path: /etc/security/access.conf
    regexp: '^#-:ALL:ALL'
    line: -:ALL:ALL
