---
# tasks file for postpatch
- name: Running post patch activities
  shell: "> /etc/motd"
 
- name: Removing figlet
  dnf:
    name: figlet
    state: absent

- name: Enable user login
  lineinfile:
    path: /etc/security/access.conf
    regexp: '^-:ALL:ALL'
    line: #-:ALL:ALL
